# Generated by Django 5.1.1 on 2024-11-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondimentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('tastes', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TastePrefModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=256, unique=True)),
                ('tastes', models.CharField(max_length=256)),
            ],
        ),
    ]
