# Generated by Django 5.1.1 on 2024-11-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condimentmodel',
            name='tastes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tasteprefmodel',
            name='tastes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tasteprefmodel',
            name='userid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
