# Generated by Django 5.1.1 on 2024-11-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_alter_condimentmodel_tastes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condimentmodel',
            name='tastes',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='tasteprefmodel',
            name='tastes',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='tasteprefmodel',
            name='userid',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
