# Generated by Django 5.1.1 on 2024-11-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_alter_condimentmodel_tastes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('condiments', models.JSONField()),
                ('is_favorite', models.BooleanField(default=False)),
                ('collection_name', models.CharField(default='My Collection', max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='condimentmodel',
            name='tastes',
            field=models.JSONField(),
        ),
    ]
