# Generated by Django 5.1.1 on 2024-11-07 11:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0007_recipemodel_description_alter_recipemodel_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='description',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='userid',
            field=models.UUIDField(default=uuid.UUID('367bf82d-5a8d-44ee-b3cc-0743dc66b5cb')),
        ),
    ]
