# Generated by Django 5.1.1 on 2024-11-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0008_alter_recipemodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='userid',
            field=models.UUIDField(),
        ),
    ]
