# Generated by Django 5.1.1 on 2024-11-07 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0009_recipemodel_is_collection_alter_recipemodel_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 18, 44, 19, 791104)),
        ),
    ]
