# Generated by Django 5.1.1 on 2024-11-07 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0010_recipemodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 19, 8, 55, 298995)),
        ),
    ]
