# Generated by Django 5.1.1 on 2024-11-07 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0011_alter_recipemodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasteprefmodel',
            name='tastes',
        ),
        migrations.AddField(
            model_name='tasteprefmodel',
            name='health_conditions',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='tasteprefmodel',
            name='sweet_offset',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 23, 29, 35, 513214)),
        ),
    ]
