# Generated by Django 5.1.1 on 2024-11-07 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0012_remove_tasteprefmodel_tastes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 23, 41, 11, 942126)),
        ),
    ]
