# Generated by Django 5.1.1 on 2024-11-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0014_alter_recipemodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasteprefmodel',
            name='salty_offset',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='tasteprefmodel',
            name='sour_offset',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='tasteprefmodel',
            name='spicy_offset',
            field=models.FloatField(default=1),
        ),
    ]
