# Generated by Django 5.1.1 on 2024-11-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0016_alter_recipemodel_userid_alter_tasteprefmodel_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasteprefmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=6, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasteprefmodel',
            name='userid',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
