# Generated by Django 5.1.1 on 2024-09-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_char', models.CharField(max_length=1024)),
                ('test_int', models.IntegerField()),
            ],
        ),
    ]
