# Generated by Django 5.1.1 on 2024-10-09 11:17

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wwcuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default=authentication.models.get_default_pfp, max_length=255, null=True, upload_to=authentication.models.get_user_pfp_path),
        ),
    ]
