# Generated by Django 5.1.1 on 2024-10-13 18:18

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_wwcuser_password_alter_wwcuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='wwcuser',
            managers=[
                ('objects', authentication.models.WWCUserManager()),
            ],
        ),
    ]
